### ISSUE TITLE
Support file-like objects

### ISSUE THREAD

**Issue by petri** [iustin/pyxattr#10]
Currently, passing a file-like object is not really supported.

It would be very useful to be able to pass in the file as a StringIO object. Or the equivalent Python3 equivalent.

**Comment by iustin** [comment]
Thanks for the bug report, but I don't understand, how would this be useful? Extended attributes are about filesystem metadata, whereas StringIO (or file _like_ objects in general) are about data only, usually in-memory data.

**Comment by petri** [comment]
I need to parse the extended attributes of a file uploaded to a WWW server (uploaded using a browser). 

Besides that, it is not unusual in app development that the file has been read elsewhere in the application (or by a third-party library) and only then it is possible (or most convenient) to do something with the extended attributes. Without access to the original file object or file path.

**Comment by iustin** [comment]
This won't work as described. Basically StringIO is just a data array, the code which reads the file would need to read the metadata and ship it along with the data. You can't retrieve the xattrs by yourself without cooperation from the original reader.

**Comment by petri** [comment]
Ok. I read somewhere that they are encoded within the file so I thought they would be "shipped" along just fine. It did not occur to me they could (and probably would have to) be stored withing the file but "out-of-band".

**Comment by iustin** [comment]
They can be encoded within the file from the filesystem point of view (I think this is the case on Windows and Mac, but not sure as I'm not familiar with those), as attribute streams; but Python regards files as a single stream of data, and metadata is separate.
