### ISSUE TITLE
pyxattr-0.5.x installation error

### ISSUE THREAD

**Issue by tanzhenchao** [iustin/pyxattr#21]
1. Installation Environment

`# cat /etc/redhat-release`

`Red Hat Enterprise Linux release 8.0 (Ootpa)`

`# pip3 -V`

`pip 9.0.3 from /usr/lib/python3.6/site-packages (python 3.6)`

2. Installation error message

`# pip3 install pyxattr-0.5.3.tar.gz`

```
    xattr.c: In function ‘merge_ns’:
    xattr.c:182:16: error: comparison of integer expressions of different signedness: ‘int’ and ‘size_t’ {aka ‘long unsigned int’} [-Werror=sign-compare]
             if(cnt > new_size || cnt < 0) {
                    ^
    xattr.c: In function ‘get_all’:
    xattr.c:532:56: error: ‘ENOATTR’ undeclared (first use in this function); did you mean ‘ENOTTY’?
                     } else if(errno == ENODATA || errno == ENOATTR) {
                                                            ^~~~~~~
                                                            ENOTTY
    xattr.c:532:56: note: each undeclared identifier is reported only once for each function it appears in
    cc1: all warnings being treated as errors
    error: command 'gcc' failed with exit status 1
```
3. How can I fix this error? Thanks!

**Comment by iustin** [comment]
Hey, sorry for the slow response, I've forgotting about this. Do you have the xattr dev library installed? Or, can you use the most recent version, which doesn't need that anymore?

**Comment by iustin** [comment]
I'm going to close this, feel free to comment/re-open if you still have problems.
