### ISSUE TITLE
PyPy3.10: `xattr.getxattr()` does not accept `pathlib.Path` whereas it works on CPython

### ISSUE THREAD

**Issue by mgorny** [iustin/pyxattr#41]
```
$ pypy3.10 -c 'import pathlib, xattr; xattr.getxattr(pathlib.Path("/"), "user.test")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: Can't convert 'PosixPath' object to str implicitly
# but
$ python3.10 -c 'import pathlib, xattr; xattr.getxattr(pathlib.Path("/"), "user.test")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
OSError: [Errno 61] No data available
```

<del>I think the line in question is:</del>

https://github.com/iustin/pyxattr/blob/1d0427598f3f3b310a118b1acd5f7b19eab1517b/xattr.c#L439

<del>I suppose CPython implicitly converts `pathlib.Path` to a string, whereas PyPy throws an error.</del>

CC @mattip

**Comment by mgorny** [comment]
Oh, sorry, I was looking at the wrong argument. It's probably https://foss.heptapod.net/pypy/pypy/-/issues/3168; i.e. `PyUnicode_FSConverter` not handling `Path` objects.

**Comment by mattip** [comment]
Could you change CI to use pypy-3.10-nightly, pypy-3.9-nightly and ping me on CI failures? https://github.com/iustin/pyxattr/blob/1d0427598f3f3b310a118b1acd5f7b19eab1517b/.github/workflows/ci.yml#L35-L37

**Comment by mattip** [comment]
I added handling for `Path` objects to latest nightlies.

**Comment by iustin** [comment]
I've switch to pypy-3.9-nightly and 3.10-nightly. The run passed: https://github.com/iustin/pyxattr/actions/runs/6982967019.

**Comment by jabbalaci** [comment]
You can always convert a `Path` object to string with `str(Path(...))` and you are done.

**Comment by mattip** [comment]
@iustin you may want to switch back to the last stable release which contains the fix I mentioned above, since using nightlies may be noisy (no guarantee they work all the time)

**Comment by iustin** [comment]
> @iustin you may want to switch back to the last stable release which contains the fix I mentioned above, since using nightlies may be noisy (no guarantee they work all the time)

I was actually going to ask about that, since I had to disable 3.10-nightly yesterday.

Is there a canonical list of the stable releases?

**Comment by mattip** [comment]
There are a few :)

The list of released downloads as a json file (consumed by the python setup github action) is [here](https://downloads.python.org/pypy/versions.json), and the downloads themselves are [here](https://downloads.python.org/pypy/)

The changelogs are [here](https://doc.pypy.org/en/latest/index-of-release-notes.html), and you can see the fix for this issue in the [version-specific changelog](https://doc.pypy.org/en/latest/release-v7.3.14.html#id1).

**Comment by iustin** [comment]
I've re-enabled pypy-3.10, and moved 3.9 from nightly to well, no nightly.

However, it's still not clear to me how to read the list of releases. E.g. from this snippet:

```
  {
    "pypy_version": "7.3.15",
    "python_version": "3.9.18",
    "stable": true,
    "latest_pypy": true,
    "date": "2024-01-15",
  …
```

How do you get to a valid `python-version: pypy-3.9`? Maybe more to the point, how can I subscribe and know when new stable versions are released? Is there a `pypy-latest' but stable?

**Comment by iustin** [comment]
I've enabled PathLib tests under pypy 3.10, which means it now runs all tests that CPython does. I'll mark this issue closed, now. Thanks all!

**Comment by mattip** [comment]
> how can I subscribe and know when new stable versions are released

You can get notified of changes to [the download site](https://downloads.python.org/pypy/) via something like https://visualping.io/

**Comment by iustin** [comment]
Well, yes, thanks, but I was hoping that there would be something built-in to GitHub actions marketplace, or similar. All good, I can periodically check myself.
