### ISSUE TITLE
Compiling on Linux Mint Petra x64

### ISSUE THREAD

**Issue by Reedyseth** [iustin/pyxattr#7]
I first of all thank you for coding this module.

I download it so that I can compile it under Linux Mint Petra on a base x64 system. The first thing that I notice weird was that that there was not configure batch on the file. I downloaded the tar.gz file from here http://pyxattr.k1024.org/downloads/ specific the version `pyxattr-0.5.5.tar.gz`.

Any insight on this will be helpful.

Regards.!!

**Comment by iustin** [comment]
Hi,

There is no configure because this is a Python extension module, which normally don't use configure scripts. Just run the `setup.py` script, eventually with `--help`, to see how to build and install it.

**Comment by Reedyseth** [comment]
> There is no configure because this is a Python extension module, which normally don't use configure scripts. Just run the setup.py script, eventually with --help, to see how to build and install it.

Awesome, thank you for your reply I will give it a try.
